// GENERATED by scripts/build-mcp.mjs from src/mcp/runGate.ts — do not edit; run `pnpm --filter workflow mcp:build`.
// An esbuild IIFE of the app's pure adapters + @bffless/workflow-agent-tools, so these rules cannot drift from the page (spec 10, D19/D22).
var __mcp = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/mcp/runGate.ts
  var runGate_exports = {};
  __export(runGate_exports, {
    ALL_SCOPE_ROLES: () => ALL_SCOPE_ROLES,
    DRIVE_KEY_HEADER: () => DRIVE_KEY_HEADER,
    SCOPE_HEADER: () => SCOPE_HEADER,
    TERMINAL_STATUSES: () => TERMINAL_STATUSES,
    admittedRun: () => admittedRun,
    gateRun: () => gateRun,
    handler: () => handler,
    hasGrant: () => hasGrant,
    header: () => header,
    isAllScopeRole: () => isAllScopeRole,
    scopeAsked: () => scopeAsked
  });

  // src/mcp/rows.ts
  function isPlainObject(value) {
    return value !== null && typeof value === "object" && !Array.isArray(value);
  }
  function rows(result) {
    if (Array.isArray(result)) return result.filter(isPlainObject);
    if (!isPlainObject(result)) return [];
    const inner = result.records ?? result.data ?? result.rows;
    return Array.isArray(inner) ? inner.filter(isPlainObject) : [];
  }
  function fieldsOf(row) {
    const fields = row.fields;
    return isPlainObject(fields) && Object.keys(fields).length > 0 ? fields : row;
  }

  // src/mcp/runGate.ts
  var ALL_SCOPE_ROLES = ["owner", "admin"];
  var TERMINAL_STATUSES = ["succeeded", "failed", "cancelled"];
  var SCOPE_HEADER = "x-workflow-scope";
  var DRIVE_KEY_HEADER = "x-workflow-drive-key";
  function isPlainObject2(value) {
    return value !== null && typeof value === "object" && !Array.isArray(value);
  }
  function str(value) {
    return typeof value === "string" ? value : "";
  }
  function header(request, name) {
    const headers = isPlainObject2(request) ? request.headers : void 0;
    if (!isPlainObject2(headers)) return "";
    const wanted = name.toLowerCase();
    for (const key of Object.keys(headers)) {
      if (key.toLowerCase() !== wanted) continue;
      const value = headers[key];
      const first = Array.isArray(value) ? value[0] : value;
      return str(first).trim();
    }
    return "";
  }
  function scopeAsked(request) {
    const query = isPlainObject2(request) ? request.query : void 0;
    const body = isPlainObject2(request) ? request.body : void 0;
    if (isPlainObject2(query) && query.scope === "all") return true;
    if (isPlainObject2(body) && body.scope === "all") return true;
    return header(request, SCOPE_HEADER) === "all";
  }
  function isAllScopeRole(projectRole) {
    return ALL_SCOPE_ROLES.indexOf(str(projectRole).toLowerCase()) !== -1;
  }
  function hasGrant(_run, _user) {
    void _run;
    void _user;
    return false;
  }
  function refuse() {
    return {
      ok: false,
      notFound: true,
      door: "",
      recordId: null,
      run: null,
      result: { ok: false, error: "run not found" }
    };
  }
  function admit(door, row, fields) {
    return {
      ok: true,
      notFound: false,
      door,
      // Wherever this CE keeps the record id — on the record, or among the
      // columns (`rows.ts` `recordIdOf` reads both) — as the string a
      // `data_update`/`data_delete` step interpolates.
      recordId: String(row.id ?? fields.id ?? "") || null,
      run: fields,
      result: null
    };
  }
  function gateRun(input) {
    const { run, runless, request } = input;
    if (runless === true) {
      return { ok: true, notFound: false, door: "runless", recordId: null, run: null, result: null };
    }
    const row = rows(run)[0];
    if (!row) return refuse();
    const f = fieldsOf(row);
    const caller = isPlainObject2(input.user) ? input.user : {};
    const startedBy = str(f.startedBy);
    if (str(caller.id) !== "" && startedBy !== "" && startedBy === str(caller.id)) return admit("owner", row, f);
    const key = header(request, DRIVE_KEY_HEADER);
    const rowKey = str(f.driveKey);
    if (key !== "" && rowKey !== "" && key === rowKey && TERMINAL_STATUSES.indexOf(str(f.status)) === -1) {
      return admit("drive", row, f);
    }
    if (scopeAsked(request) && isAllScopeRole(caller.projectRole)) return admit("all", row, f);
    if (hasGrant(f, caller)) return admit("grant", row, f);
    return refuse();
  }
  function admittedRun(steps) {
    if (!isPlainObject2(steps)) return void 0;
    const gate = steps.runGate;
    if (!isPlainObject2(gate) || gate.ok !== true) return void 0;
    const row = rows(steps.run)[0];
    return row ? fieldsOf(row) : void 0;
  }
  function handler(data) {
    const steps = isPlainObject2(data) && isPlainObject2(data.steps) ? data.steps : {};
    const runless = [steps.route, steps.confine, steps.normalize].some(
      (step) => isPlainObject2(step) && step.runless === true
    );
    return gateRun({
      run: steps.run,
      runless,
      request: isPlainObject2(data) ? data.request : void 0,
      user: isPlainObject2(data) ? data.user : void 0
    });
  }
  return __toCommonJS(runGate_exports);
})();

function handler(data) { return __mcp.handler(data) }
