// GENERATED by scripts/build-mcp.mjs from src/mcp/wellKnown.ts — do not edit; run `pnpm --filter workflow mcp:build`.
// An esbuild IIFE of the app's pure adapters + @bffless/workflow-agent-tools, so these rules cannot drift from the page (spec 10, D19/D22).
var __mcp = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/mcp/wellKnown.ts
  var wellKnown_exports = {};
  __export(wellKnown_exports, {
    MCP_PATH: () => MCP_PATH,
    authorizationServerOf: () => authorizationServerOf,
    documentFor: () => documentFor,
    handler: () => handler
  });

  // ../../packages/workflow-agent-tools/dist/schemas.js
  var RUN_ID = {
    type: "string",
    description: "The run to act on. Optional where a current run exists (the harness page); required over the MCP endpoint."
  };
  var IMPL = { type: "string", description: "The implementation alias, e.g. `hello`." };
  var WORKFLOW = {
    type: "string",
    description: "The workflow id \u2014 the file base name minus `.workflow.yaml`, e.g. `interactive`."
  };
  var LIST_SCHEMA = {
    type: "object",
    properties: { impl: { ...IMPL, description: "Only this implementation." } },
    required: [],
    additionalProperties: false
  };
  var DESCRIBE_SCHEMA = {
    type: "object",
    properties: { impl: IMPL, workflow: WORKFLOW },
    required: ["impl", "workflow"],
    additionalProperties: false
  };
  var START_SCHEMA = {
    type: "object",
    properties: {
      impl: IMPL,
      workflow: WORKFLOW,
      inputs: {
        type: "object",
        description: "Values for `on.manual.inputs`, keyed by input name. An omitted input takes its declared default; a `file` input is a whole File ref (`{ path, name, contentType, size, url }`), never a bare path or a URL. Pass `{}` for a workflow with no inputs.",
        additionalProperties: true
      }
    },
    required: ["impl", "workflow", "inputs"],
    additionalProperties: false
  };
  var STATUS_SCHEMA = {
    type: "object",
    properties: { runId: RUN_ID },
    required: [],
    additionalProperties: false
  };
  var OUTPUTS_SCHEMA = STATUS_SCHEMA;
  var CANCEL_SCHEMA = STATUS_SCHEMA;
  var AWAIT_SCHEMA = {
    type: "object",
    properties: {
      runId: RUN_ID,
      until: {
        type: "string",
        enum: ["waiting", "terminal"],
        description: "`waiting`: resolve as soon as the run needs input (a step is `waiting`) or ends; `terminal`: resolve only when the run ends."
      },
      timeoutMs: {
        type: "integer",
        minimum: 1,
        maximum: 6e5,
        description: "How long to wait before answering with the current snapshot and `timedOut: true` (default 120000)."
      }
    },
    required: ["until"],
    additionalProperties: false
  };
  var RUNS_SCHEMA = {
    type: "object",
    properties: {
      impl: { ...IMPL, description: "The implementation alias; defaults to the current run\u2019s (or the page\u2019s) on the harness page." },
      workflow: { ...WORKFLOW, description: "The workflow id; defaults to the current run\u2019s (or the page\u2019s) on the harness page." },
      status: { type: "string", enum: ["running", "succeeded", "failed", "cancelled"], description: "Only runs in this status." },
      limit: { type: "integer", minimum: 1, maximum: 50, description: "At most this many runs, newest first (default 20)." }
    },
    required: [],
    additionalProperties: false
  };
  var SUBMIT_STEP_SCHEMA = {
    type: "object",
    properties: {
      runId: RUN_ID,
      step: { type: "string", description: "The waiting step\u2019s key, `<job>/<index>/<step>` \u2014 as listed in the snapshot\u2019s `waitingOn`." },
      values: {
        type: "object",
        description: "For a `form` step: a value per field, keyed by field name (a `choice` over File refs takes the ref\u2019s `path`). For an `island` step: the step\u2019s declared outputs, keyed by output name.",
        additionalProperties: true
      }
    },
    required: ["step", "values"],
    additionalProperties: false
  };
  var SIGN_SCHEMA = {
    type: "object",
    properties: {
      runId: RUN_ID,
      path: {
        type: "string",
        description: "A File ref\u2019s `path` \u2014 an uploads-relative key under `workflows/`. Nothing else is signable."
      }
    },
    required: ["path"],
    additionalProperties: false
  };
  var RESUME_SCHEMA = {
    type: "object",
    properties: { runId: { ...RUN_ID, description: "The `running` run to take over." } },
    required: ["runId"],
    additionalProperties: false
  };

  // ../../packages/workflow-agent-tools/dist/scopes.js
  var SCOPES = ["workflow:read", "workflow:run", "workflow:files"];
  var TOOL_SCOPES = {
    "workflow.list": "workflow:read",
    "workflow.describe": "workflow:read",
    "workflow.status": "workflow:read",
    "workflow.await": "workflow:read",
    "workflow.runs": "workflow:read",
    "workflow.outputs": "workflow:read",
    "workflow.start": "workflow:run",
    "workflow.submitStep": "workflow:run",
    "workflow.cancel": "workflow:run",
    "workflow.resume": "workflow:run",
    "workflow.sign": "workflow:files"
  };

  // ../../packages/workflow-agent-tools/dist/catalog.js
  var TOOL_NAMES = [
    "workflow.list",
    "workflow.describe",
    "workflow.start",
    "workflow.status",
    "workflow.await",
    "workflow.runs",
    "workflow.submitStep",
    "workflow.outputs",
    "workflow.sign",
    "workflow.cancel",
    "workflow.resume"
  ];
  var DESCRIPTIONS = {
    "workflow.list": "List the implementations published to this harness and their workflows, each with its `headlessSafe` mark (whether every interactive step declares what to do without a person).",
    "workflow.describe": "Describe one workflow before deciding a run can complete without a person: its inputs (types, required, defaults), its outputs, the job/step graph in dependency order, and each interactive step\u2019s `headless` declaration.",
    "workflow.start": "Start a run of a workflow with the given inputs. Validated exactly as the kickoff form validates a person\u2019s values; a refusal names each bad input. On the harness page it returns the run id and its first snapshot and moves the page to the run. Over the MCP endpoint it dispatches the implementation\u2019s headless driver and answers `pending` with the run id; poll workflow.status until the row exists (about a minute), then complete its interactive steps here.",
    "workflow.status": "The run snapshot: status, the steps in flight, every reached step\u2019s status, the outputs so far, and `waitingOn` \u2014 for each waiting step what would satisfy it (its kind, its evaluated inputs, an island\u2019s declared outputs and src).",
    "workflow.await": 'Wait until the run needs input (`until: "waiting"`) or ends (`until: "terminal"`), then return its snapshot. The polite alternative to polling `workflow.status`.',
    "workflow.runs": "Past runs of one workflow, newest first: id, status, when it started and ended, and which steps it is waiting on.",
    "workflow.submitStep": "Complete a waiting interactive step, or open it for the person. A `form` step takes a value per field; an `island` step takes its declared outputs. Validated by the same checks a person\u2019s submit runs; a refusal names each bad value. In an agent host that renders this tool\u2019s UI, call it with `values: {}` for an island or form step: the step\u2019s own UI is shown and the person completes it there \u2014 do not invent values for them.",
    "workflow.outputs": "The run\u2019s outputs \u2014 File refs (`{ path, name, contentType, size, url }`), never bytes.",
    "workflow.sign": "Exchange a File ref\u2019s `path` for a short-lived presigned GET URL (`{ url, expiresIn }`), the same one islands get to show media.",
    "workflow.cancel": "Cancel the run. Server-side pipeline jobs already enqueued keep running.",
    "workflow.resume": "Take over a `running` run whose driver went away (an expired lease). On the harness page this surface drives it from here. Over the MCP endpoint it dispatches the implementation\u2019s headless driver to resume the run \u2014 how a run answered here continues without a person on the page."
  };
  var SCHEMAS = {
    "workflow.list": LIST_SCHEMA,
    "workflow.describe": DESCRIBE_SCHEMA,
    "workflow.start": START_SCHEMA,
    "workflow.status": STATUS_SCHEMA,
    "workflow.await": AWAIT_SCHEMA,
    "workflow.runs": RUNS_SCHEMA,
    "workflow.submitStep": SUBMIT_STEP_SCHEMA,
    "workflow.outputs": OUTPUTS_SCHEMA,
    "workflow.sign": SIGN_SCHEMA,
    "workflow.cancel": CANCEL_SCHEMA,
    "workflow.resume": RESUME_SCHEMA
  };
  var CATALOG = Object.freeze(TOOL_NAMES.map((name) => Object.freeze({
    name,
    description: DESCRIPTIONS[name],
    inputSchema: SCHEMAS[name],
    annotations: Object.freeze({ readOnlyHint: TOOL_SCOPES[name] === "workflow:read" }),
    scope: TOOL_SCOPES[name]
  })));
  var BY_NAME = new Map(CATALOG.map((tool) => [tool.name, tool]));

  // src/mcp/wellKnown.ts
  var MCP_PATH = "/api/workflow/mcp";
  function authorizationServerOf(host) {
    const hostname = host.split(":")[0];
    const labels = hostname.split(".");
    const adminHost = labels.length > 1 ? ["admin", ...labels.slice(1)].join(".") : host;
    return `https://${adminHost}`;
  }
  function header(headers, name) {
    const value = headers?.[name] ?? headers?.[name.toLowerCase()];
    const first = Array.isArray(value) ? value[0] : value;
    return typeof first === "string" ? first.split(",")[0].trim() : "";
  }
  function documentFor(host) {
    return {
      resource: `https://${host}${MCP_PATH}`,
      authorization_servers: [authorizationServerOf(host)],
      scopes_supported: [...SCOPES],
      bearer_methods_supported: ["header"],
      resource_name: "BFFless Workflow",
      resource_documentation: "https://github.com/bffless/apps/blob/main/apps/workflow/docs/spec/10-agent-embedding.md"
    };
  }
  function handler(data) {
    const headers = data.request?.headers ?? {};
    const host = header(headers, "x-forwarded-host") || header(headers, "host");
    if (host === "") return { json: JSON.stringify({ error: "no_host", message: "the request names no host" }), ok: false };
    return { json: JSON.stringify(documentFor(host)), ok: true };
  }
  return __toCommonJS(wellKnown_exports);
})();

function handler(data) { return __mcp.handler(data) }
