order: 0
pipeline:
  name: Upload youtube_thumbnail
  description: Upload files to youtube_thumbnail
  steps:
    - id: upload
      name: upload
      handler: file_upload_handler
      config:
        subDir: youtube-thumbnail
        schemaId: $schema:youtube_thumbnail
        dateBucket: false
        maxFileSize: 10485760
        allowedMimeTypes:
          - image/*
      isEnabled: true
    - id: response
      name: Return Upload Result
      handler: response_handler
      config:
        body: "{{{steps.upload}}}"
        status: 200
        contentType: application/json
      isEnabled: true
  validators:
    - type: auth_required
      config:
        allowApiKey: true
description: Upload files to youtube_thumbnail
