// GENERATED by scripts/build-mcp.mjs from src/mcp/plan.ts — do not edit; run `pnpm --filter workflow mcp:build`.
// An esbuild IIFE of the app's pure adapters + @bffless/workflow-agent-tools, so this rule cannot drift from the page (spec 10, D19/D22).
var __mcp = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/mcp/plan.ts
  var plan_exports = {};
  __export(plan_exports, {
    aliasNames: () => aliasNames,
    handler: () => handler,
    queryOf: () => queryOf
  });

  // src/mcp/polyfills.ts
  var SCHEME = /^[a-z][a-z0-9+.-]*:/i;
  function isDoubleDot(segment) {
    const s = segment.toLowerCase();
    return s === ".." || s === ".%2e" || s === "%2e." || s === "%2e%2e";
  }
  function isSingleDot(segment) {
    const s = segment.toLowerCase();
    return s === "." || s === "%2e";
  }
  var URL = class {
    pathname;
    constructor(input, base) {
      void base;
      let path = String(input).replace(/\\/g, "/");
      if (SCHEME.test(path)) {
        const afterScheme = path.slice(path.indexOf(":") + 1);
        if (afterScheme.startsWith("//")) {
          const slash = afterScheme.indexOf("/", 2);
          path = slash === -1 ? "/" : afterScheme.slice(slash);
        } else {
          path = afterScheme;
        }
      } else if (path.startsWith("//")) {
        const slash = path.indexOf("/", 2);
        path = slash === -1 ? "/" : path.slice(slash);
      }
      path = path.split("#")[0].split("?")[0];
      const segments = path.split("/");
      if (segments[0] === "") segments.shift();
      const out = [];
      for (let i = 0; i < segments.length; i++) {
        const segment = segments[i];
        const last = i === segments.length - 1;
        if (isDoubleDot(segment)) {
          out.pop();
          if (last) out.push("");
        } else if (isSingleDot(segment)) {
          if (last) out.push("");
        } else {
          out.push(segment);
        }
      }
      this.pathname = "/" + out.join("/");
    }
  };

  // ../../packages/workflow-lint/dist/expressions/functions.js
  var STATUS_FUNCTIONS = ["success", "failure", "always", "cancelled"];
  var KNOWN_FUNCTIONS = [
    "contains",
    "startswith",
    "endswith",
    "format",
    "join",
    "tojson",
    "fromjson",
    "length",
    "pluck",
    ...STATUS_FUNCTIONS
  ];

  // src/lib/runner/results.ts
  var RESPONSE_BUDGET_BYTES = 256 * 1024;

  // src/lib/runner/adapters/declared.ts
  function obj(value) {
    return value !== null && typeof value === "object" ? value : {};
  }

  // src/lib/runner/adapters/island.ts
  var HAS_SCHEME = /^[a-z][a-z0-9+.-]*:/i;
  var ENCODED_OR_BACKSLASH = /[\\%]/;
  function inside(url, prefix) {
    try {
      return new URL(url, "https://harness.invalid").pathname.startsWith(prefix);
    } catch {
      return false;
    }
  }
  function resolveSrc(impl, src, kind = "island") {
    const bad = (why) => {
      throw new Error(`${kind} src ${src}: ${why}`);
    };
    if (src === "") bad("must not be empty");
    if (ENCODED_OR_BACKSLASH.test(src)) bad("must not contain a backslash or a percent-escape");
    if (!src.startsWith("/w/") && (src.startsWith("/") || HAS_SCHEME.test(src))) {
      bad("must be relative to the implementation bundle or under /w/");
    }
    const last = src.split("/").at(-1);
    if (last === "" || last === ".") bad("must name a file");
    const url = src.startsWith("/w/") ? src : `/w/${impl}/${src}`;
    if (src.split("/").includes("..") || !inside(url, `/w/${impl}/`)) {
      bad(`must resolve inside /w/${impl}/`);
    }
    return url;
  }
  var HOST_TOOLS = /* @__PURE__ */ new Map([
    ["workflow.submit", "submit"],
    ["workflow/submit", "submit"],
    ["workflow.annotate", "annotate"],
    ["workflow/annotate", "annotate"],
    ["workflow.sign", "sign"],
    ["workflow/sign", "sign"]
  ]);
  function methodOf(meta) {
    return obj(obj(meta).bffless).method === "GET" ? "GET" : "POST";
  }
  function rejected(reason) {
    return { kind: "rejected", reason };
  }
  function resolveToolName(impl, name, meta) {
    if (typeof name !== "string" || name === "") return rejected("a tool name is required");
    if (/\s/.test(name)) return rejected(`tool "${name}": a tool name may not contain whitespace`);
    const host = HOST_TOOLS.get(name);
    if (host) return { kind: "host", tool: host };
    if (name.startsWith("/")) {
      return rejected(`tool "${name}": absolute paths are not callable from an island`);
    }
    if (ENCODED_OR_BACKSLASH.test(name)) {
      return rejected(`tool "${name}": a tool name may not contain a backslash or a percent-escape`);
    }
    const path = name.includes("/") ? name : name.split(".").join("/");
    const segments = path.split("/");
    const url = `/api/${impl}/${path}`;
    if (segments.some((s) => s === "" || s === "." || s === "..") || !inside(url, `/api/${impl}/`)) {
      return rejected(`tool "${name}": resolves outside /api/${impl}/`);
    }
    return { kind: "pipeline", path, method: methodOf(meta), url };
  }
  var ANNOTATION_BUDGET = {
    /** Annotations per step, the recorded ones included. */
    count: 100,
    /** JSON bytes of a step's annotations, the recorded ones included. */
    bytes: 64 * 1024,
    /** JSON bytes of one summary. */
    summaryBytes: 16 * 1024
  };

  // src/mcp/ids.ts
  function workflowId(file) {
    const base = file.split("/").pop() ?? file;
    return base.replace(/\.workflow\.ya?ml$/i, "").replace(/\.ya?ml$/i, "");
  }

  // src/mcp/rows.ts
  function isPlainObject2(value) {
    return value !== null && typeof value === "object" && !Array.isArray(value);
  }
  function rows(result) {
    if (Array.isArray(result)) return result.filter(isPlainObject2);
    if (!isPlainObject2(result)) return [];
    const inner = result.records ?? result.data ?? result.rows;
    return Array.isArray(inner) ? inner.filter(isPlainObject2) : [];
  }
  function fieldsOf(row) {
    const fields = row.fields;
    return isPlainObject2(fields) && Object.keys(fields).length > 0 ? fields : row;
  }

  // ../../packages/workflow-agent-tools/dist/schemas.js
  var RUN_ID = {
    type: "string",
    description: "The run to act on. Optional where a current run exists (the harness page); required over the MCP endpoint."
  };
  var IMPL = { type: "string", description: "The implementation alias, e.g. `hello`." };
  var WORKFLOW = {
    type: "string",
    description: "The workflow id \u2014 the file base name minus `.workflow.yaml`, e.g. `interactive`."
  };
  var LIST_SCHEMA = {
    type: "object",
    properties: { impl: { ...IMPL, description: "Only this implementation." } },
    required: [],
    additionalProperties: false
  };
  var DESCRIBE_SCHEMA = {
    type: "object",
    properties: { impl: IMPL, workflow: WORKFLOW },
    required: ["impl", "workflow"],
    additionalProperties: false
  };
  var START_SCHEMA = {
    type: "object",
    properties: {
      impl: IMPL,
      workflow: WORKFLOW,
      inputs: {
        type: "object",
        description: "Values for `on.manual.inputs`, keyed by input name. An omitted input takes its declared default; a `file` input is a whole File ref (`{ path, name, contentType, size, url }`), never a bare path or a URL. Pass `{}` for a workflow with no inputs.",
        additionalProperties: true
      }
    },
    required: ["impl", "workflow", "inputs"],
    additionalProperties: false
  };
  var STATUS_SCHEMA = {
    type: "object",
    properties: { runId: RUN_ID },
    required: [],
    additionalProperties: false
  };
  var OUTPUTS_SCHEMA = STATUS_SCHEMA;
  var CANCEL_SCHEMA = STATUS_SCHEMA;
  var AWAIT_SCHEMA = {
    type: "object",
    properties: {
      runId: RUN_ID,
      until: {
        type: "string",
        enum: ["waiting", "terminal"],
        description: "`waiting`: resolve as soon as the run needs input (a step is `waiting`) or ends; `terminal`: resolve only when the run ends."
      },
      timeoutMs: {
        type: "integer",
        minimum: 1,
        maximum: 6e5,
        description: "How long to wait before answering with the current snapshot and `timedOut: true` (default 120000)."
      }
    },
    required: ["until"],
    additionalProperties: false
  };
  var RUNS_SCHEMA = {
    type: "object",
    properties: {
      impl: { ...IMPL, description: "The implementation alias; defaults to the current run\u2019s (or the page\u2019s) on the harness page." },
      workflow: { ...WORKFLOW, description: "The workflow id; defaults to the current run\u2019s (or the page\u2019s) on the harness page." },
      status: { type: "string", enum: ["running", "succeeded", "failed", "cancelled"], description: "Only runs in this status." },
      limit: { type: "integer", minimum: 1, maximum: 50, description: "At most this many runs, newest first (default 20)." }
    },
    required: [],
    additionalProperties: false
  };
  var SUBMIT_STEP_SCHEMA = {
    type: "object",
    properties: {
      runId: RUN_ID,
      step: { type: "string", description: "The waiting step\u2019s key, `<job>/<index>/<step>` \u2014 as listed in the snapshot\u2019s `waitingOn`." },
      values: {
        type: "object",
        description: "For a `form` step: a value per field, keyed by field name (a `choice` over File refs takes the ref\u2019s `path`). For an `island` step: the step\u2019s declared outputs, keyed by output name.",
        additionalProperties: true
      }
    },
    required: ["step", "values"],
    additionalProperties: false
  };
  var SIGN_SCHEMA = {
    type: "object",
    properties: {
      runId: RUN_ID,
      path: {
        type: "string",
        description: "A File ref\u2019s `path` \u2014 an uploads-relative key under `workflows/`. Nothing else is signable."
      }
    },
    required: ["path"],
    additionalProperties: false
  };
  var RESUME_SCHEMA = {
    type: "object",
    properties: { runId: { ...RUN_ID, description: "The `running` run to take over." } },
    required: ["runId"],
    additionalProperties: false
  };

  // ../../packages/workflow-agent-tools/dist/scopes.js
  var TOOL_SCOPES = {
    "workflow.list": "workflow:read",
    "workflow.describe": "workflow:read",
    "workflow.status": "workflow:read",
    "workflow.await": "workflow:read",
    "workflow.runs": "workflow:read",
    "workflow.outputs": "workflow:read",
    "workflow.start": "workflow:run",
    "workflow.submitStep": "workflow:run",
    "workflow.cancel": "workflow:run",
    "workflow.resume": "workflow:run",
    "workflow.sign": "workflow:files"
  };

  // ../../packages/workflow-agent-tools/dist/catalog.js
  var TOOL_NAMES = [
    "workflow.list",
    "workflow.describe",
    "workflow.start",
    "workflow.status",
    "workflow.await",
    "workflow.runs",
    "workflow.submitStep",
    "workflow.outputs",
    "workflow.sign",
    "workflow.cancel",
    "workflow.resume"
  ];
  var DESCRIPTIONS = {
    "workflow.list": "List the implementations published to this harness and their workflows, each with its `headlessSafe` mark (whether every interactive step declares what to do without a person).",
    "workflow.describe": "Describe one workflow before deciding a run can complete without a person: its inputs (types, required, defaults), its outputs, the job/step graph in dependency order, and each interactive step\u2019s `headless` declaration.",
    "workflow.start": "Start a run of a workflow with the given inputs. Validated exactly as the kickoff form validates a person\u2019s values; a refusal names each bad input. Returns the run id and its first snapshot, and moves the page to the run.",
    "workflow.status": "The run snapshot: status, the steps in flight, every reached step\u2019s status, the outputs so far, and `waitingOn` \u2014 for each waiting step what would satisfy it (its kind, its evaluated inputs, an island\u2019s declared outputs and src).",
    "workflow.await": 'Wait until the run needs input (`until: "waiting"`) or ends (`until: "terminal"`), then return its snapshot. The polite alternative to polling `workflow.status`.',
    "workflow.runs": "Past runs of one workflow, newest first: id, status, when it started and ended, and which steps it is waiting on.",
    "workflow.submitStep": "Complete a waiting interactive step, or open it for the person. A `form` step takes a value per field; an `island` step takes its declared outputs. Validated by the same checks a person\u2019s submit runs; a refusal names each bad value. In an agent host that renders this tool\u2019s UI, call it with `values: {}` for an island step: the step\u2019s own island is shown and the person completes it there \u2014 do not invent values for them.",
    "workflow.outputs": "The run\u2019s outputs \u2014 File refs (`{ path, name, contentType, size, url }`), never bytes.",
    "workflow.sign": "Exchange a File ref\u2019s `path` for a short-lived presigned GET URL (`{ url, expiresIn }`), the same one islands get to show media.",
    "workflow.cancel": "Cancel the run. Server-side pipeline jobs already enqueued keep running.",
    "workflow.resume": "Take over a `running` run whose driver went away (an expired lease) so this surface drives it from here \u2014 how an agent adopts a run another tab or host abandoned."
  };
  var SCHEMAS = {
    "workflow.list": LIST_SCHEMA,
    "workflow.describe": DESCRIBE_SCHEMA,
    "workflow.start": START_SCHEMA,
    "workflow.status": STATUS_SCHEMA,
    "workflow.await": AWAIT_SCHEMA,
    "workflow.runs": RUNS_SCHEMA,
    "workflow.submitStep": SUBMIT_STEP_SCHEMA,
    "workflow.outputs": OUTPUTS_SCHEMA,
    "workflow.sign": SIGN_SCHEMA,
    "workflow.cancel": CANCEL_SCHEMA,
    "workflow.resume": RESUME_SCHEMA
  };
  var CATALOG = Object.freeze(TOOL_NAMES.map((name) => Object.freeze({
    name,
    description: DESCRIPTIONS[name],
    inputSchema: SCHEMAS[name],
    annotations: Object.freeze({ readOnlyHint: TOOL_SCOPES[name] === "workflow:read" }),
    scope: TOOL_SCOPES[name]
  })));
  var BY_NAME = new Map(CATALOG.map((tool) => [tool.name, tool]));

  // src/mcp/hostTools.ts
  var RUN_ID2 = { type: "string", description: "The run the island belongs to." };
  var STEP = { type: "string", description: "The step key, `<job>/<index>/<step>`, of the waiting island step." };
  var APP_ONLY = { ui: { visibility: ["app"] } };
  var HOST_TOOLS2 = Object.freeze([
    {
      name: "workflow.submit",
      description: "Complete the waiting island step of a run with its declared outputs \u2014 the island's own `workflow.submit` (spec 04), answered server-side: validated against the step's declared output map exactly as the harness page validates it, then written to the step row. Refused while a harness tab still drives the run.",
      inputSchema: {
        type: "object",
        properties: { runId: RUN_ID2, step: STEP, outputs: { type: "object", description: "The values for the step\u2019s declared outputs.", additionalProperties: true } },
        required: ["runId", "step", "outputs"],
        additionalProperties: false
      },
      _meta: APP_ONLY
    },
    {
      name: "workflow.annotate",
      description: "Record annotations and/or a summary on the waiting island step \u2014 the island's own `workflow.annotate` (spec 04), budgeted per step exactly as on the harness page.",
      inputSchema: {
        type: "object",
        properties: {
          runId: RUN_ID2,
          step: STEP,
          annotations: { type: "array", description: "Entries of `{ level: notice|warning|error, message, title? }`.", items: { type: "object", additionalProperties: true } },
          summary: { type: "string" }
        },
        required: ["runId", "step"],
        additionalProperties: false
      },
      _meta: APP_ONLY
    },
    {
      name: "workflow.pipeline",
      description: "Call one of the run's own implementation's pipelines on the island's behalf \u2014 a tool name resolves to `/api/<impl>/<path>` (dots as slashes) and is fenced to that implementation exactly as on the harness page (spec 04).",
      inputSchema: {
        type: "object",
        properties: {
          runId: RUN_ID2,
          step: STEP,
          name: { type: "string", description: "The pipeline\u2019s tool name, e.g. `echo` or `video.slice`." },
          arguments: { type: "object", description: "The JSON body (POST) or query (GET).", additionalProperties: true },
          method: { type: "string", enum: ["GET", "POST"], description: "Defaults to POST." }
        },
        required: ["runId", "step", "name"],
        additionalProperties: false
      },
      _meta: APP_ONLY
    },
    {
      name: "workflow.stepView",
      description: "What the step view needs to mount a waiting island: the island HTML (unchanged, fetched from the implementation's bundle), the step's persisted inputs (its tool-input arguments), and its declared outputs.",
      inputSchema: {
        type: "object",
        properties: { runId: RUN_ID2, step: STEP },
        required: ["runId", "step"],
        additionalProperties: false
      },
      _meta: APP_ONLY
    }
  ]);
  var HOST_TOOL_NAMES = new Set(HOST_TOOLS2.map((tool) => tool.name));

  // src/mcp/jsonrpc.ts
  var PROTOCOL_VERSIONS = ["2025-06-18", "2025-03-26", "2024-11-05"];
  var LATEST_PROTOCOL_VERSION = PROTOCOL_VERSIONS[0];

  // src/mcp/route.ts
  var LIST_FANOUT = 3;

  // src/mcp/plan.ts
  function isPlainObject3(value) {
    return value !== null && typeof value === "object" && !Array.isArray(value);
  }
  function aliasNames(body) {
    const list = Array.isArray(body) ? body : isPlainObject3(body) && Array.isArray(body.data) ? body.data : [];
    return list.map((entry) => isPlainObject3(entry) && typeof entry.alias === "string" ? entry.alias : "").filter((alias) => alias !== "");
  }
  function handler(data) {
    const route = data.steps?.route;
    const harnessAlias = typeof data.deployment?.alias === "string" ? data.deployment.alias : "workflow";
    const plan = {
      has1: false,
      has2: false,
      has3: false,
      url1: "",
      url2: "",
      url3: "",
      aliases: [],
      skipped: [],
      hasYaml: false,
      yamlUrl: "",
      listing: null,
      hasIsland: false,
      islandUrl: "",
      islandError: "",
      isPipelinePost: false,
      isPipelineGet: false,
      pipelineUrl: "",
      pipelineBody: {},
      pipelineError: ""
    };
    if (!route) return plan;
    const indexUrlOf = (alias) => `${route.appOrigin}/w/${alias}/.bffless/workflows/index.json`;
    if (route.isList && route.appOrigin !== "") {
      let wanted;
      if (route.impl !== "") {
        wanted = [route.impl];
      } else {
        const aliases = data.steps.aliases;
        wanted = aliases?.ok === true ? aliasNames(aliases.body).filter((alias) => alias !== harnessAlias) : [];
      }
      plan.aliases = wanted.slice(0, LIST_FANOUT);
      plan.skipped = wanted.slice(LIST_FANOUT);
      const [url1 = "", url2 = "", url3 = ""] = plan.aliases.map(indexUrlOf);
      Object.assign(plan, { has1: url1 !== "", url1, has2: url2 !== "", url2, has3: url3 !== "", url3 });
    }
    if (route.isDescribe) {
      const index = data.steps.index;
      const body = index?.ok === true && isPlainObject3(index.body) ? index.body : null;
      const workflows = body && Array.isArray(body.workflows) ? body.workflows : [];
      const listing = workflows.find(
        (entry) => isPlainObject3(entry) && typeof entry.file === "string" && workflowId(entry.file) === route.workflow
      );
      if (listing && route.appOrigin !== "") {
        plan.listing = listing;
        plan.hasYaml = true;
        plan.yamlUrl = `${route.appOrigin}/w/${route.impl}/.bffless/workflows/${listing.file}`;
      }
    }
    if (route.isIslandUri) {
      try {
        const url = resolveSrc(route.impl, route.rest);
        if (route.appOrigin !== "") {
          plan.hasIsland = true;
          plan.islandUrl = `${route.appOrigin}${url}`;
        }
      } catch (err) {
        plan.islandError = err instanceof Error ? err.message : String(err);
      }
    }
    if (route.tool === "workflow.stepView" || route.tool === "workflow.pipeline") {
      const runRow = rows(data.steps.run)[0];
      const run = runRow ? fieldsOf(runRow) : null;
      const impl = run && typeof run.impl === "string" ? run.impl : "";
      if (!run || impl === "") {
        const missing = `No such run: ${route.runId}`;
        plan.islandError = missing;
        plan.pipelineError = missing;
        return plan;
      }
      if (route.tool === "workflow.stepView") {
        const row = rows(data.steps.steps).map(fieldsOf).find((r) => r.key === route.key);
        const src = row ? declaredSrc(run.definition, String(row.job ?? ""), String(row.step ?? "")) : "";
        if (!row) plan.islandError = `No such step: ${route.key}`;
        else if (src === "") plan.islandError = `${route.key}: the run's definition snapshot declares no island src`;
        else {
          try {
            const url = resolveSrc(impl, src);
            if (route.appOrigin !== "") {
              plan.hasIsland = true;
              plan.islandUrl = `${route.appOrigin}${url}`;
            }
          } catch (err) {
            plan.islandError = err instanceof Error ? err.message : String(err);
          }
        }
      } else {
        const name = typeof route.args.name === "string" ? route.args.name : "";
        const method = route.args.method === "GET" ? "GET" : "POST";
        const target = resolveToolName(impl, name, { bffless: { method } });
        const args = isPlainObject3(route.args.arguments) ? route.args.arguments : {};
        if (target.kind === "rejected") plan.pipelineError = target.reason;
        else if (target.kind === "host") plan.pipelineError = `tool "${name}": workflow.${target.tool} is a host tool \u2014 call it directly`;
        else if (route.appOrigin === "") plan.pipelineError = "the request named no host";
        else if (target.method === "GET") {
          plan.isPipelineGet = true;
          plan.pipelineUrl = `${route.appOrigin}${target.url}${queryOf(args)}`;
        } else {
          plan.isPipelinePost = true;
          plan.pipelineUrl = `${route.appOrigin}${target.url}`;
          plan.pipelineBody = args;
        }
      }
    }
    return plan;
  }
  function declaredSrc(definition, job, stepId) {
    if (!isPlainObject3(definition) || !isPlainObject3(definition.jobs)) return "";
    const jobDecl = definition.jobs[job];
    if (!isPlainObject3(jobDecl) || !Array.isArray(jobDecl.steps)) return "";
    const step = jobDecl.steps.find((entry) => isPlainObject3(entry) && entry.id === stepId);
    const withDecl = step && isPlainObject3(step.with) ? step.with : void 0;
    return withDecl && typeof withDecl.src === "string" ? withDecl.src : "";
  }
  function queryOf(args) {
    const pairs = Object.entries(args).map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(typeof value === "string" ? value : JSON.stringify(value))}`);
    return pairs.length ? `?${pairs.join("&")}` : "";
  }
  return __toCommonJS(plan_exports);
})();

function handler(data) { return __mcp.handler(data) }
