// GENERATED by scripts/build-mcp.mjs from src/mcp/reply.ts — do not edit; run `pnpm --filter workflow mcp:build`.
// An esbuild IIFE of the app's pure adapters + @bffless/workflow-agent-tools, so this rule cannot drift from the page (spec 10, D19/D22).
var __mcp = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/mcp/reply.ts
  var reply_exports = {};
  __export(reply_exports, {
    handler: () => handler
  });
  function handler() {
    return { placeholder: "reply" };
  }
  return __toCommonJS(reply_exports);
})();

function handler(data) { return __mcp.handler(data) }
