// @vitest-environment node
/**
 * The committed `*.fn.js` bundles of the MCP endpoint rule are what
 * `deploy-proxy-rules` syncs and what the catalog bundle ships, so they must
 * be (1) fresh — rebuilt from `src/mcp/**` — (2) admissible to CE's
 * function_handler, whose static scan refuses a fixed list of patterns, and
 * (3) runnable in the sandbox CE actually gives them, which has none of
 * Node's or the browser's globals. This suite rebuilds each entry in memory,
 * compares, scans, and runs it in a `node:vm` context shaped like CE's.
 */
import { readFileSync, readdirSync, statSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { join } from 'node:path'
import { ENTRIES, OUT_DIR, SET, bundle, outFile, packageJsonForRev, renderedRules, sourceRev } from '../../scripts/build-mcp.mjs'
import { runInCeSandbox } from '../test/ceSandbox'
import { HELLO_INDEX, INTERACTIVE_YAML, RUN_ID, runRow, stepRows } from './fixtures/index'
import { handler as replySource } from './reply'
import { handler as replyDescribeSource } from './replyDescribe'
import { handler as routeSource } from './route'
import { handler as runGateSource } from './runGate'
import { REFUSALS } from './refusals'
import { DESCRIBE_ELSEWHERE, type StepOutputs } from './reply'
import { TOOLS_PATH } from './route'

/**
 * The byte budget of every committed `mcp-fn/*.fn.js` (apps#721), a little
 * above its size when the budget was set. `deploy-proxy-rules` inlines a
 * bundle's text into EVERY rule whose step points at it — `reply` into
 * fifteen — so a bundle's bytes are paid per referencing rule, per push, and
 * the backend's rule cache holds them all. Nothing capped this before, which
 * is how `reply` reached 265 KB (a YAML parser only `workflow.describe`
 * needs). Raising a budget is allowed; do it in the PR that needs it, and say
 * why — it is the point where a heavy import gets noticed.
 */
const BUDGETS: Record<string, number> = {
  route: 14_500,
  plan: 19_000,
  merge: 27_000,
  reply: 32_500,
  replyDescribe: 150_000,
  drivePlan: 11_500,
  driveGate: 14_500,
  runGate: 3_500,
}

/**
 * Verbatim `PROHIBITED_PATTERNS` from
 * `repos/ce/apps/backend/src/pipelines/function-runner.service.ts` (v0.4.40).
 * A bundle that trips one is refused at rule sync with "Invalid code".
 */
const PROHIBITED_PATTERNS = [
  /\beval\s*\(/,
  /\bnew\s+Function\s*\(/,
  /\bFunction\s*\(/,
  /\brequire\s*\(/,
  /\bimport\s*\(/,
  /\bprocess\s*\./,
  /\bglobal\s*\./,
  /\bglobalThis\s*\./,
  /\.__proto__/,
  /\bconstructor\s*\[/,
  /\bconstructor\s*\./,
  /\bBuffer\s*\(/,
  /\bBuffer\s*\./,
]

const SMOKE_DATA = {
  request: { body: {}, query: {}, headers: {}, method: 'POST', path: '/api/workflow/mcp-tools/status' },
  steps: {},
  deployment: { owner: 'o', repo: 'r', commitSha: 'c', alias: 'workflow' },
}

describe('MCP endpoint bundles', () => {
  for (const name of ENTRIES) {
    describe(name, () => {
      const committed = readFileSync(outFile(name), 'utf8')

      it('is fresh (run `pnpm --filter workflow mcp:build` after editing src/mcp/**)', async () => {
        expect(committed).toBe(await bundle(name))
      }, 30_000)

      it("carries none of CE's prohibited patterns", () => {
        for (const pattern of PROHIBITED_PATTERNS) {
          const hit = committed.match(pattern)
          expect(hit, `${pattern} at …${committed.slice(Math.max(0, (hit?.index ?? 0) - 80), (hit?.index ?? 0) + 40)}…`).toBeNull()
        }
      })

      it("runs in CE's sandbox and answers an object", async () => {
        const result = await runInCeSandbox(committed, SMOKE_DATA)
        expect(result).toBeTypeOf('object')
        expect(result).not.toBeNull()
      })
    })
  }
})

describe('the bundle byte budgets (apps#721)', () => {
  it('budgets every entry, and every file under mcp-fn/ is an entry', () => {
    expect(Object.keys(BUDGETS).sort()).toEqual([...ENTRIES].sort())
    expect(readdirSync(OUT_DIR).filter((f) => f.endsWith('.fn.js')).sort()).toEqual(ENTRIES.map((name) => `${name}.fn.js`).sort())
  })

  for (const name of ENTRIES) {
    it(`${name}.fn.js stays within ${BUDGETS[name]} bytes`, () => {
      expect(statSync(outFile(name)).size).toBeLessThanOrEqual(BUDGETS[name])
    })
  }

  it('still says how it was made, minified or not', () => {
    for (const name of ENTRIES) {
      const text = readFileSync(outFile(name), 'utf8')
      expect(text.startsWith(`// GENERATED by scripts/build-mcp.mjs from src/mcp/${name}.ts`), name).toBe(true)
    }
  })

  it('keeps the YAML parser out of every bundle but replyDescribe', () => {
    // The yaml package's core schema tag prefix: present wherever the parser is bundled.
    const PARSER = 'tag:yaml.org,2002:'
    expect(readFileSync(outFile('replyDescribe'), 'utf8')).toContain(PARSER)
    for (const name of ENTRIES.filter((n) => n !== 'replyDescribe')) {
      expect(readFileSync(outFile(name), 'utf8'), name).not.toContain(PARSER)
    }
  })
})

describe('workflow.describe through its own bundle (apps#721)', () => {
  const DEPLOYMENT = { owner: 'o', repo: 'r', commitSha: 'c', alias: 'workflow' }
  const request = { body: { impl: 'hello', workflow: 'interactive' }, headers: { host: 'h.example' }, method: 'POST', path: `${TOOLS_PATH}describe` }
  const user = { id: 'member@example.com', email: 'member@example.test', role: 'user', projectRole: 'contributor' }
  const http = (body: unknown, status = 200) => ({ ok: status < 400, status, body })
  const committed = (name: string) => readFileSync(outFile(name), 'utf8')

  /** The describe rule's steps, run as CE runs them: the committed route, plan and reply bundles in its sandbox. */
  async function describeSteps(yaml: unknown): Promise<StepOutputs> {
    const route = (await runInCeSandbox(committed('route'), { request, deployment: DEPLOYMENT, user })) as StepOutputs['route']
    const index = http(HELLO_INDEX)
    const plan = (await runInCeSandbox(committed('plan'), { request, steps: { route, index }, deployment: DEPLOYMENT, user })) as StepOutputs['plan']
    return { route, index, plan, yaml } as StepOutputs
  }

  it('parses the published YAML in the sandbox and answers exactly what the source handler answers', async () => {
    const steps = await describeSteps(http(INTERACTIVE_YAML))
    const out = (await runInCeSandbox(committed('replyDescribe'), { request, steps, deployment: DEPLOYMENT, user })) as { json: string }
    expect(out.json).toBe(replyDescribeSource({ request, steps, deployment: DEPLOYMENT }).json)
    const body = JSON.parse(out.json) as { isError?: boolean; content: { text: string }[]; structuredContent: { jobs: Array<{ id: string }> } }
    expect(body.isError).toBeUndefined()
    expect(body.content[0].text).toMatch(/^Interactive hello \(hello\/interactive\): 2 inputs/)
    expect(body.structuredContent.jobs.map((job) => job.id)).toEqual(['greet', 'analyze', 'pick', 'card', 'review'])
  })

  it('refuses YAML that does not parse, as before', async () => {
    const steps = await describeSteps(http('jobs: ['))
    const out = (await runInCeSandbox(committed('replyDescribe'), { request, steps, deployment: DEPLOYMENT, user })) as { json: string }
    expect(JSON.parse(out.json).structuredContent.errors).toEqual({ workflow: REFUSALS.doesNotLint })
    expect(out.json).toBe(replyDescribeSource({ request, steps, deployment: DEPLOYMENT }).json)
  })

  it('is not answered by the shared reply bundle', async () => {
    const steps = await describeSteps(http(INTERACTIVE_YAML))
    const out = (await runInCeSandbox(committed('reply'), { request, steps, deployment: DEPLOYMENT, user })) as { json: string }
    expect(JSON.parse(out.json).structuredContent.errors).toEqual({ tool: DESCRIBE_ELSEWHERE })
  })

  it('is wired: only the describe rule runs replyDescribe; every other reply step runs reply', async () => {
    const codes = (await renderedRules())
      .filter(([rel]) => rel.includes('/mcp-tools/') || rel.includes('/mcp-resources/'))
      .map(([rel, text]) => [rel, [...text.matchAll(/code: (\S+)/g)].map((m) => m[1]).filter((c) => /reply(Describe)?\.fn\.js$/.test(c))] as const)
    for (const [rel, refs] of codes) {
      if (rel.includes('mcp-resources/step-view/')) continue // no reply step: it answers the step view's HTML
      const want = rel.includes('/mcp-tools/describe/') ? 'replyDescribe.fn.js' : 'reply.fn.js'
      expect(refs.map((c) => c.split('/').pop()), rel).toEqual([want])
    }
    expect(codes.filter(([, refs]) => refs.some((c) => c.endsWith('replyDescribe.fn.js')))).toHaveLength(1)
  })
})

/**
 * A gated tool end to end through the COMMITTED, minified bundles (apps#721):
 * the rules' `condition:` strings read bundle output keys by name
 * (`steps.route.needsRun`, `steps.runGate.ok`), so a bundler setting that
 * renamed a property would skip steps silently. Each committed bundle's
 * answer must equal its source handler's, key for key.
 */
describe('workflow.status through the committed bundles', () => {
  const DEPLOYMENT = { owner: 'o', repo: 'r', commitSha: 'c', alias: 'workflow' }
  const user = { id: 'member@example.com', email: 'member@example.test', role: 'user', projectRole: 'contributor' }
  const request = { body: { runId: RUN_ID }, headers: { host: 'h.example' }, method: 'POST', path: `${TOOLS_PATH}status` }
  const committed = (name: string) => readFileSync(outFile(name), 'utf8')

  it('route → runGate → reply answer what the sources answer, and the keys the rule conditions read are there', async () => {
    const route = (await runInCeSandbox(committed('route'), { request, deployment: DEPLOYMENT, user })) as Record<string, unknown>
    expect(route).toEqual(routeSource({ request, deployment: DEPLOYMENT, user } as Parameters<typeof routeSource>[0]))
    expect(route.needsRun).toBe(true)
    expect(route.runId).toBe(RUN_ID)

    const run = [runRow()]
    const gateData = { steps: { route, run }, request, user }
    const runGate = (await runInCeSandbox(committed('runGate'), gateData)) as Record<string, unknown>
    expect(runGate).toEqual(runGateSource(gateData as Parameters<typeof runGateSource>[0]))
    expect(runGate.ok).toBe(true)

    const steps = { route, run, runGate, steps: stepRows() } as unknown as StepOutputs
    const out = (await runInCeSandbox(committed('reply'), { request, steps, deployment: DEPLOYMENT, user })) as { json: string }
    expect(out.json).toBe(replySource({ request, steps, deployment: DEPLOYMENT }).json)
    expect(JSON.parse(out.json).isError).toBeUndefined()
  })
})

describe('the rendered MCP rules', () => {
  it('are fresh (run `pnpm --filter workflow mcp:build` after editing src/mcp/mcpConfig.ts or the generator)', async () => {
    const files = await renderedRules()
    expect(files.length).toBe(1 + 15 + 2)
    for (const [rel, text] of files) {
      expect(readFileSync(join(SET, rel), 'utf8'), rel).toBe(text)
    }
  }, 30_000)
})

describe('the source revision (apps#587)', () => {
  it('is 8 hex chars, stable across calls, and the rendered endpoint rule carries it', async () => {
    const rev = sourceRev()
    expect(rev).toMatch(/^[0-9a-f]{8}$/)
    expect(sourceRev()).toBe(rev)
    const endpoint = (await renderedRules()).find(([rel]) => rel === 'rules/api/workflow/mcp/any.rule.yaml')![1]
    expect(endpoint).toContain(`ui://bffless/workflow/step-view.${rev}.html`)
  })

  it("ignores package.json's version (a release PR bumps it and cannot run mcp:build) but not its dependencies", () => {
    const at = (version: string, dep = '^1.0.0') =>
      packageJsonForRev(JSON.stringify({ name: 'workflow', version, dependencies: { react: dep } }))
    expect(at('1.2.1')).toBe(at('1.3.0'))
    expect(at('1.2.1')).not.toBe(at('1.2.1', '^2.0.0'))
  })
})
