import { test, after } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, rmSync, symlinkSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { stripReviewEnvelope } from './strip-review-envelope.mjs'

// pr-review.yml prepends the header and appends the footer itself, so the agent emitting
// either gets it posted twice. The two live regressions are apps#662 (header duplicated)
// and apps#660 (whole review fenced as ```markdown, header and footer copied from the
// round-1 comment the agent had just read).
//
// The other half of these tests is what the stripper must NOT do. A review of the reviewer
// quotes all three markers as content, and the reports that need unwrapping are the same
// ones that carry fenced blocks of their own — so "leaves it alone" is the assertion that
// matters most here. A wrong strip loses a review silently; a missed one is a scruffy
// comment.

const HEADER = '## 🤖 Automated apps review'
const FOOTER = '<sub>Generated by the `apps-pr-review` agent. Advisory only — not an approval.</sub>'
const lines = (...xs) => xs.join('\n')

test('a clean report passes through untouched', () => {
  const report = '### Verdict\n\nSafe to merge.\n'
  assert.equal(stripReviewEnvelope(report), report)
})

test('drops a header the agent emitted (apps#662)', () => {
  const out = stripReviewEnvelope(`${HEADER}\n\nReviewing **PR #662** (round 1).\n\n### Verdict\n\nSafe.\n`)
  assert.equal(out, 'Reviewing **PR #662** (round 1).\n\n### Verdict\n\nSafe.\n')
})

test('drops a header under a preamble line, keeping the preamble', () => {
  const out = stripReviewEnvelope(`Reviewing PR #7.\n\n${HEADER}\n\n### Verdict\n\nSafe.\n`)
  assert.equal(out, 'Reviewing PR #7.\n\n### Verdict\n\nSafe.\n')
})

test('unwraps a ```markdown fence around the whole report', () => {
  const out = stripReviewEnvelope(lines('```markdown', '### Verdict', '', 'Safe.', '```', ''))
  assert.equal(out, '### Verdict\n\nSafe.\n')
})

test('unwraps fence, preamble, header and footer together (apps#660)', () => {
  const out = stripReviewEnvelope(
    lines('Reviewing PR #660.', '', '```markdown', HEADER, '', '### Verdict', '', 'Safe.', '', '---', FOOTER, '```', ''),
  )
  assert.equal(out, '### Verdict\n\nSafe.\n')
})

test('unwraps an outer fence while keeping a fenced checklist entry inside it', () => {
  const out = stripReviewEnvelope(
    lines('```markdown', HEADER, '', '### Checklist candidates', '', '```', 'entry text', '```', '```', ''),
  )
  assert.equal(out, lines('### Checklist candidates', '', '```', 'entry text', '```') + '\n')
})

test('leaves a report that quotes the header in a finding whole', () => {
  const report = lines(
    '### Verdict',
    '',
    'Safe.',
    '',
    '### Findings',
    '',
    `**1.** CI already prints \`${HEADER}\` itself, so the agent must not.`,
    '',
  )
  assert.equal(stripReviewEnvelope(report), report)
})

test('leaves a report that quotes the footer mid-review whole', () => {
  const report = lines('### Findings', '', `The posted comment ends with \`${FOOTER}\`.`, '', '### Tests', '', 'None missing.', '')
  assert.equal(stripReviewEnvelope(report), report)
})

test('leaves a report that opens with prose and closes with a fenced block', () => {
  // The shape a fence-counting heuristic mistakes for an outer wrapper: the checklist
  // entry Step 4 asks for sits last, and its closing fence is the report's last line.
  const report = lines('Verification:', '', '```', 'pnpm test', '```', '', '### Checklist candidates', '', '```', 'entry', '```', '')
  assert.equal(stripReviewEnvelope(report), report)
})

test('leaves a bare fence it has no evidence wraps the report', () => {
  const report = lines('```', '### Verdict', '', 'Safe.', '```', '')
  assert.equal(stripReviewEnvelope(report), report)
})

test('drops the footer and its --- separator, not a --- inside the review', () => {
  const out = stripReviewEnvelope(`### Verdict\n\nSafe.\n\n---\n\n### Tests\n\nNone missing.\n\n---\n${FOOTER}\n`)
  assert.equal(out, '### Verdict\n\nSafe.\n\n---\n\n### Tests\n\nNone missing.\n')
})

// bffless/apps#401: a main-module guard that compares argv[1] to import.meta.url without
// realpath'ing both sides is false through a symlink, and the script silently no-ops.
{
  const tmpDirs = []
  after(() => {
    for (const dir of tmpDirs) rmSync(dir, { recursive: true, force: true })
  })

  test('runs when invoked through a symlink, same as invoked directly', () => {
    const script = fileURLToPath(new URL('./strip-review-envelope.mjs', import.meta.url))
    const linkDir = mkdtempSync(join(tmpdir(), 'strip-review-envelope-link-'))
    tmpDirs.push(linkDir)
    const link = join(linkDir, 'strip-review-envelope.mjs')
    symlinkSync(script, link)

    assert.throws(
      () => execFileSync(process.execPath, [link], { encoding: 'utf8', stdio: 'pipe' }),
      (err) => {
        assert.equal(err.status, 2)
        assert.match(err.stderr, /^usage: node scripts\/strip-review-envelope\.mjs <report\.md>/)
        return true
      },
    )
  })
}
