import { test } from 'node:test'
import assert from 'node:assert/strict'
import { stripReviewEnvelope } from './strip-review-envelope.mjs'

// pr-review.yml prepends the header and appends the footer itself, so the agent emitting
// either gets it posted twice. These cases are the two live regressions: apps#662 (header
// duplicated) and apps#660 (whole review fenced as ```markdown, header and footer copied
// from the round-1 comment the agent had just read). What must not regress in the other
// direction is a clean report, and a fenced code block that is part of the review.

const HEADER = '## 🤖 Automated apps review'
const FOOTER = '<sub>Generated by the `apps-pr-review` agent. Advisory only — not an approval.</sub>'

test('a clean report passes through untouched', () => {
  const report = '### Verdict\n\nSafe to merge.\n'
  assert.equal(stripReviewEnvelope(report), report)
})

test('drops a header the agent emitted (apps#662)', () => {
  const out = stripReviewEnvelope(`${HEADER}\n\nReviewing **PR #662** (round 1).\n\n### Verdict\n\nSafe.\n`)
  assert.ok(!out.includes(HEADER))
  assert.ok(out.startsWith('Reviewing **PR #662** (round 1).'))
})

test('unwraps a whole-report ```markdown fence, header and footer (apps#660)', () => {
  const out = stripReviewEnvelope(
    ['Reviewing PR #660.', '', '```markdown', HEADER, '', '### Verdict', '', 'Safe.', '', '---', FOOTER, '```', ''].join('\n'),
  )
  assert.equal(out, '### Verdict\n\nSafe.\n')
})

test('keeps a fenced code block that belongs to the review', () => {
  const report = ['### Checklist candidates', '', '```', 'entry text', '```', '', 'Trailing prose.', ''].join('\n')
  assert.equal(stripReviewEnvelope(report), report)
})

test('keeps a report that both opens and closes with its own fenced blocks', () => {
  const report = ['```yaml', 'a: 1', '```', '', 'Prose.', '', '```sh', 'pnpm test', '```', ''].join('\n')
  assert.equal(stripReviewEnvelope(report), report)
})

test('drops the footer and its --- separator, not a --- inside the review', () => {
  const out = stripReviewEnvelope(`### Verdict\n\nSafe.\n\n---\n\n### Tests\n\nNone missing.\n\n---\n${FOOTER}\n`)
  assert.equal(out, '### Verdict\n\nSafe.\n\n---\n\n### Tests\n\nNone missing.\n')
})
