#!/usr/bin/env node
// Build the MCP rules (spec 10, D22 GA; Phase 3 plan, Task B1):
//
//  1. the four function bundles — each `src/mcp/<entry>.ts` becomes one esbuild
//     IIFE committed under `.bffless/proxy-rules/workflow/mcp-fn/<entry>.fn.js`,
//     the `code:` file every tool rule's function step points at (the CLI
//     confines `code:` to the rule-set directory, so one copy serves all);
//  2. the endpoint rule — `rules/api/workflow/mcp/rule.yaml`, ONE `mcp_handler`
//     step whose config is rendered from `src/mcp/mcpConfig.ts` (the catalog's
//     descriptors byte for byte, D19);
//  3. one sibling rule per tool under `rules/api/workflow/mcp-tools/<name>/post/`
//     with exactly the steps that tool needs and `requiredScopes` from the
//     catalog's map (D23), plus the two resource rules under `mcp-resources/`.
//
// CE runs a function's code inside `(async function () { <code>; __result__ =
// await handler(data) })()` in a vm context (function-runner.service.ts), so
// the bundle's `handler` must be a plain declaration in that scope: the IIFE
// is assigned to `__mcp` and a trailing `function handler` forwards to it.
// `src/mcp/polyfills.ts` is injected for the two globals the sandbox lacks.
//
// `src/mcp/bundle.test.ts` rebuilds everything in memory and fails when a
// committed file is stale, so `pnpm --filter workflow mcp:build` after editing
// `src/mcp/**` is part of the verify chain.
import { build } from 'esbuild'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { stringify } from 'yaml'

const app = join(dirname(fileURLToPath(import.meta.url)), '..')
const SET = join(app, '.bffless/proxy-rules/workflow')

/** One entry per function step shared by the tool rules, plus the RFC 9728 document (`wellKnown`, one rule). */
export const ENTRIES = ['route', 'plan', 'merge', 'reply', 'wellKnown']

export const OUT_DIR = join(SET, 'mcp-fn')

const HEADER = (name) =>
  `// GENERATED by scripts/build-mcp.mjs from src/mcp/${name}.ts — do not edit; run \`pnpm --filter workflow mcp:build\`.\n` +
  `// An esbuild IIFE of the app's pure adapters + @bffless/workflow-agent-tools, so these rules cannot drift from the page (spec 10, D19/D22).\n`

const FOOTER = `\nfunction handler(data) { return __mcp.handler(data) }\n`

/** The committed path of one entry's bundle. */
export function outFile(name) {
  return join(OUT_DIR, `${name}.fn.js`)
}

/** The bundle text for one entry — what the committed file must equal. */
export async function bundle(name) {
  const result = await build({
    entryPoints: [join(app, 'src/mcp', `${name}.ts`)],
    bundle: true,
    write: false,
    format: 'iife',
    globalName: '__mcp',
    platform: 'neutral',
    target: 'es2022',
    treeShaking: true,
    minify: false,
    legalComments: 'none',
    logLevel: 'silent',
    inject: [join(app, 'src/mcp/polyfills.ts')],
    absWorkingDir: app,
  })
  return HEADER(name) + result.outputFiles[0].text + FOOTER
}

/** `src/mcp/mcpConfig.ts`, bundled for Node and imported — the one source of the rendered rules. */
async function loadConfig() {
  const result = await build({
    entryPoints: [join(app, 'src/mcp/mcpConfig.ts')],
    bundle: true,
    write: false,
    format: 'esm',
    platform: 'node',
    target: 'es2022',
    logLevel: 'silent',
    absWorkingDir: app,
  })
  const url = `data:text/javascript;base64,${Buffer.from(result.outputFiles[0].text).toString('base64')}`
  return import(url)
}

const GENERATED = '# GENERATED by scripts/build-mcp.mjs from src/mcp/mcpConfig.ts — do not edit; run `pnpm --filter workflow mcp:build`.\n'

const yaml = (doc) => GENERATED + stringify(doc, { lineWidth: 0 })

/** `code:` for a shared bundle, relative to the rule file's directory. */
const codeRef = (ruleDir, entry) => relative(ruleDir, outFile(entry)).split('\\').join('/')

/** The static step definitions the tool rules share (the prototype's 24, split per tool). */
function stepDefs(ruleDir) {
  const fn = (id) => ({ id, name: id, handler: 'function_handler', code: codeRef(ruleDir, id) })
  const http = (id, condition, url, path, extra = {}) => ({
    id,
    name: id,
    handler: 'http_request',
    config: {
      condition,
      url,
      method: 'GET',
      headers: { 'x-original-uri': path, 'x-forwarded-host': 'steps.route.host' },
      forwardAuth: true,
      failOnError: false,
      ...extra,
    },
  })
  const query = (id, condition, schema, limit, filters) => ({
    id,
    name: id,
    handler: 'data_query',
    config: { condition, schemaId: `$schema:${schema}`, limit, filters },
  })
  return {
    route: fn('route'),
    plan: fn('plan'),
    merge: fn('merge'),
    reply: fn('reply'),
    run: query('run', 'steps.route.needsRun', 'workflow_runs', 1, { runId: { op: 'eq', value: 'steps.route.runId' } }),
    steps: query('steps', 'steps.route.needsRun', 'workflow_run_steps', 1000, { runId: { op: 'eq', value: 'steps.route.runId' } }),
    runs: query('runs', 'steps.route.isRuns', 'workflow_runs', 50, { impl: { op: 'eq', value: 'steps.route.impl' }, workflow: { op: 'eq', value: 'steps.route.workflow' } }),
    waiting: query('waiting', 'steps.route.isRuns', 'workflow_run_steps', 1000, { status: { op: 'eq', value: 'waiting' } }),
    // CE's alias API in-process (spec 06); the caller's credential is forwarded, so CE answers the member's own alias list.
    aliases: { id: 'aliases', name: 'aliases', handler: 'http_request', config: { condition: 'steps.route.isAliases', url: 'steps.route.aliasesUrl', method: 'GET', forwardAuth: true, failOnError: false } },
    index: http('index', 'steps.route.isDescribe', 'steps.route.indexUrl', 'steps.route.indexPath'),
    index1: http('index1', 'steps.plan.has1', 'steps.plan.url1', 'steps.plan.path1'),
    index2: http('index2', 'steps.plan.has2', 'steps.plan.url2', 'steps.plan.path2'),
    index3: http('index3', 'steps.plan.has3', 'steps.plan.url3', 'steps.plan.path3'),
    yaml: http('yaml', 'steps.plan.hasYaml', 'steps.plan.yamlUrl', 'steps.plan.yamlPath'),
    island: http('island', 'steps.plan.hasIsland', 'steps.plan.islandUrl', 'steps.plan.islandPath'),
    pipelinePost: http('pipelinePost', 'steps.plan.isPipelinePost', 'steps.plan.pipelineUrl', 'steps.plan.pipelinePath', { method: 'POST', body: 'steps.plan.pipelineBody' }),
    pipelineGet: http('pipelineGet', 'steps.plan.isPipelineGet', 'steps.plan.pipelineUrl', 'steps.plan.pipelinePath'),
    signed: { id: 'signed', name: 'signed', handler: 'signed_url', config: { condition: 'steps.route.isSign', path: 'steps.route.signStoragePath', expiresIn: 3600 } },
    update: {
      id: 'update',
      name: 'update',
      handler: 'data_update',
      config: {
        condition: 'steps.merge.update',
        schemaId: '$schema:workflow_run_steps',
        recordId: 'steps.merge.recordId',
        fields: Object.fromEntries(
          ['status', 'attempt', 'inputs', 'response', 'outputs', 'error', 'summary', 'annotations', 'log', 'logId', 'startedAt', 'finishedAt', 'heartbeatAt'].map((f) => [f, `steps.merge.fields.${f}`]),
        ),
      },
    },
  }
}

const respondJson = { id: 'respond', name: 'respond', handler: 'response_handler', config: { body: '{{{steps.reply.json}}}', status: 200, headers: { 'Cache-Control': 'no-store' }, contentType: 'application/json' } }

/** Every generated rule file: `[relative path under the set, text]`. */
export async function renderedRules() {
  const cfg = await loadConfig()
  const files = []
  const config = cfg.mcpHandlerConfig()

  files.push([
    'rules/api/workflow/mcp/any.rule.yaml',
    yaml({
      methods: ['GET', 'POST', 'DELETE'],
      targetUrl: 'pipeline',
      order: 30,
      pipeline: {
        name: 'MCP endpoint',
        description:
          "POST /api/workflow/mcp — the harness's MCP server as ONE rule on CE's generic mcp_handler (spec 10, D22 GA). tools/list IS the catalog: this config is rendered from @bffless/workflow-agent-tools at build time and held fresh by bundle.test.ts (D19). Every tool is a sibling rule under mcp-tools/, executed in-process as the caller with its own requiredScopes (D23); GET/DELETE → 405 (stateless, no SSE).",
        steps: [{ id: 'mcp', name: 'mcp', handler: 'mcp_handler', config }],
        validators: [{ type: 'auth_required', config: { allowApiKey: true } }],
      },
      description:
        "The MCP endpoint (spec 10, D22): stateless Streamable HTTP over one mcp_handler step. Bearer app tokens are the credential (D23); a tool's scope is enforced by its sibling rule. no-store: every answer is per-message.",
    }),
  ])

  for (const tool of cfg.ALL_TOOLS) {
    const short = cfg.shortName(tool)
    const rel = `rules/api/workflow/mcp-tools/${short}/post/rule.yaml`
    const defs = stepDefs(join(SET, dirname(rel)))
    const steps = cfg.TOOL_STEPS[tool].map((key) => defs[key])
    files.push([
      rel,
      yaml({
        targetUrl: 'pipeline',
        order: 40,
        pipeline: {
          name: `MCP tool ${tool}`,
          description: `One catalog tool as one rule (spec 10, GA shape): CE's mcp_handler invokes it in-process as the caller; the body is the tool's arguments, the answer is a catalog CallToolResult. The validator is where the tool's scope is enforced (D23). Functions are the shared bundles under mcp-fn/ (route → the flags this rule's static steps read; reply → the result).`,
          steps: [...steps, respondJson],
          validators: [{ type: 'auth_required', config: { allowApiKey: true, requiredScopes: [cfg.toolScope(tool)] } }],
        },
        description: `${tool} over the MCP endpoint — scope ${cfg.toolScope(tool)}.`,
      }),
    ])
  }

  {
    const rel = 'rules/api/workflow/mcp-resources/get/rule.yaml'
    const defs = stepDefs(join(SET, dirname(rel)))
    files.push([
      rel,
      yaml({
        targetUrl: 'pipeline',
        order: 41,
        pipeline: {
          name: 'MCP resources list',
          description: "What the harness enumerates for resources/list: every island of every published implementation (spec 10). CE's mcp_handler adds the step view (a static resource of the endpoint config) and every resource's generated _meta.ui CSP.",
          steps: [...cfg.RESOURCES_STEPS.map((key) => defs[key]), respondJson],
          validators: [{ type: 'auth_required', config: { allowApiKey: true, requiredScopes: ['workflow:read'] } }],
        },
        description: 'The MCP resources list — scope workflow:read.',
      }),
    ])
  }
  {
    const rel = 'rules/api/workflow/mcp-resources/step-view/get/rule.yaml'
    const defs = stepDefs(join(SET, dirname(rel)))
    files.push([
      rel,
      yaml({
        targetUrl: 'pipeline',
        order: 41,
        pipeline: {
          name: 'MCP step view resource',
          description: 'The step view (ui://bffless/workflow/step-view.html, spec 10): /step.html fetched in-process from the harness bundle and answered as text/html, the way resources/read serves it.',
          steps: [
            defs.route,
            { id: 'stepView', name: 'stepView', handler: 'http_request', config: { condition: 'steps.route.isStepView', url: 'steps.route.stepViewUrl', method: 'GET', headers: { 'x-original-uri': 'steps.route.stepViewPath', 'x-forwarded-host': 'steps.route.host' }, forwardAuth: true, failOnError: false } },
            { id: 'respond', name: 'respond', handler: 'response_handler', config: { body: '{{{steps.stepView.body}}}', status: 200, headers: { 'Cache-Control': 'no-store' }, contentType: 'text/html; charset=utf-8' } },
          ],
          validators: [{ type: 'auth_required', config: { allowApiKey: true, requiredScopes: ['workflow:read'] } }],
        },
        description: 'The step view as a ui:// resource — scope workflow:read.',
      }),
    ])
  }
  return files
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const write = (path, text) => {
    let same = false
    try {
      same = readFileSync(path, 'utf8') === text
    } catch {
      same = false
    }
    if (!same) {
      mkdirSync(dirname(path), { recursive: true })
      writeFileSync(path, text)
    }
    console.log(`${same ? 'unchanged' : 'wrote'} ${relative(app, path)} (${text.length} bytes)`)
  }
  for (const name of ENTRIES) write(outFile(name), await bundle(name))
  for (const [rel, text] of await renderedRules()) write(join(SET, rel), text)
}

export { SET, pathToFileURL }
