#!/usr/bin/env node
// Build the MCP endpoint's function_handler bundles (spec 10, D22; Phase 2 plan,
// Decision 1): each `src/mcp/<entry>.ts` becomes one esbuild IIFE committed as
// `.bffless/proxy-rules/workflow/rules/api/workflow/mcp/post/<entry>.fn.js`,
// the `code:` file of one pipeline step. The bundles import the agent tool
// catalog and the app's pure adapters, so `tools/list` *is* `CATALOG` and the
// fence *is* `resolveToolName` — the rule cannot drift from the page.
//
// CE runs a function's code inside `(async function () { <code>; __result__ =
// await handler(data) })()` in a vm context (function-runner.service.ts), so
// the bundle's `handler` must be a plain declaration in that scope: the IIFE
// is assigned to `__mcp` and a trailing `function handler` forwards to it.
// `src/mcp/polyfills.ts` is injected for the two globals the sandbox lacks.
//
// `src/mcp/bundle.test.ts` rebuilds in memory and fails when a committed
// bundle is stale, so `pnpm --filter workflow mcp:build` after editing
// `src/mcp/**` is part of the verify chain.
import { build } from 'esbuild'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const app = join(dirname(fileURLToPath(import.meta.url)), '..')

/** One entry per function step of `mcp/post/rule.yaml`, in pipeline order. */
export const ENTRIES = ['route', 'plan', 'merge', 'reply']

export const OUT_DIR = join(app, '.bffless/proxy-rules/workflow/rules/api/workflow/mcp/post')

const HEADER = (name) =>
  `// GENERATED by scripts/build-mcp.mjs from src/mcp/${name}.ts — do not edit; run \`pnpm --filter workflow mcp:build\`.\n` +
  `// An esbuild IIFE of the app's pure adapters + @bffless/workflow-agent-tools, so this rule cannot drift from the page (spec 10, D19/D22).\n`

const FOOTER = `\nfunction handler(data) { return __mcp.handler(data) }\n`

/** The committed path of one entry's bundle. */
export function outFile(name) {
  return join(OUT_DIR, `${name}.fn.js`)
}

/** The bundle text for one entry — what the committed file must equal. */
export async function bundle(name) {
  const result = await build({
    entryPoints: [join(app, 'src/mcp', `${name}.ts`)],
    bundle: true,
    write: false,
    format: 'iife',
    globalName: '__mcp',
    platform: 'neutral',
    target: 'es2022',
    treeShaking: true,
    minify: false,
    legalComments: 'none',
    logLevel: 'silent',
    inject: [join(app, 'src/mcp/polyfills.ts')],
    absWorkingDir: app,
  })
  return HEADER(name) + result.outputFiles[0].text + FOOTER
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  for (const name of ENTRIES) {
    const text = await bundle(name)
    const out = outFile(name)
    let same = false
    try {
      same = readFileSync(out, 'utf8') === text
    } catch {
      same = false
    }
    if (!same) {
      mkdirSync(OUT_DIR, { recursive: true })
      writeFileSync(out, text)
    }
    console.log(`${same ? 'unchanged' : 'wrote'} ${out} (${text.length} bytes)`)
  }
}
