import { describe, expect, it } from 'vitest'
import { Report, exitCodeOf, toMarkdown } from '../src/report.js'

describe('Report', () => {
  it('passes when every check passes', () => {
    const r = new Report('hello', 'https://x.test')
    expect(r.expect('a', true, 1)).toBe(true)
    const out = r.finish()
    expect(out.ok).toBe(true)
    expect(exitCodeOf(out)).toBe(0)
    expect(out.checks.a).toEqual({ pass: true, evidence: 1 })
  })
  it('fails on one FAIL and keeps recording after it', () => {
    const r = new Report('hello', 'https://x.test')
    r.expect('a', false, { got: 1 })
    r.expect('b', true)
    const out = r.finish()
    expect(out.ok).toBe(false)
    expect(exitCodeOf(out)).toBe(1)
    expect(Object.keys(out.checks)).toEqual(['a', 'b'])
  })
  it('blocked wins over fail and exits 2', () => {
    const r = new Report('studio-headless', 'https://x.test')
    r.expect('a', false)
    r.block('no credentials')
    const out = r.finish()
    expect(out.blocked).toBe('no credentials')
    expect(exitCodeOf(out)).toBe(2)
  })
  it('dedups run ids and counts kickoffs', () => {
    const r = new Report('w', 'h')
    r.run('run_1'); r.run('run_1'); r.kickoff()
    const out = r.finish()
    expect(out.runIds).toEqual(['run_1'])
    expect(out.spend.studioKickoffs).toBe(1)
  })
  it('renders README-style rows', () => {
    const r = new Report('hello', 'https://x.test')
    r.expect('D6.signedImg', true, 'https://storage.googleapis.com/…')
    r.expect('D4.sandboxed', false, 'origin=https://workflow.j5s.dev')
    const md = toMarkdown(r.finish())
    expect(md).toContain('- [x] **D6.signedImg — PASS.** "https://storage.googleapis.com/…"')
    expect(md).toContain('- [ ] **D4.sandboxed — FAIL.** "origin=https://workflow.j5s.dev"')
  })
  it('renders a BLOCKED header', () => {
    const r = new Report('hello', 'h'); r.block('harness unreachable')
    expect(toMarkdown(r.finish())).toMatch(/^\*\*BLOCKED — harness unreachable\*\*/)
  })
  it('scoped() prefixes check names but records on the parent report', () => {
    const r = new Report('w', 'h')
    const scoped = r.scoped('dispatch.')
    expect(scoped.expect('a', true, 1)).toBe(true)
    const out = r.finish()
    expect(out.checks['dispatch.a']).toEqual({ pass: true, evidence: 1 })
  })
  it('guard() turns a throw into a FAIL per listed name left unrecorded, keeps what fn recorded, and resolves false without blocking', async () => {
    const r = new Report('hello', 'h')
    const ok = await r.guard(['D6.a', 'D6.b'], async () => {
      r.expect('D6.a', true, 1)
      throw new Error('locator.waitFor: Timeout 30000ms exceeded')
    })
    expect(ok).toBe(false)
    const out = r.finish()
    expect(out.checks['D6.a']).toEqual({ pass: true, evidence: 1 })
    expect(out.checks['D6.b']).toEqual({ pass: false, evidence: 'Error: locator.waitFor: Timeout 30000ms exceeded' })
    expect(out.ok).toBe(false)
    expect(out.blocked).toBeUndefined()
    expect(exitCodeOf(out)).toBe(1)
  })
  it('guard() caps the evidence at 400 chars, like the CLI', async () => {
    const r = new Report('w', 'h')
    await r.guard(['a'], () => { throw new Error('x'.repeat(1000)) })
    expect(String(r.finish().checks.a.evidence)).toHaveLength(400)
  })
  it('guard() records only what a non-throwing fn expected and resolves true', async () => {
    const r = new Report('w', 'h')
    const ok = await r.guard(['a', 'b'], async () => { r.expect('a', true) })
    expect(ok).toBe(true)
    expect(Object.keys(r.finish().checks)).toEqual(['a'])
  })
  it('throws on a duplicate check name, but scoped names do not collide with the same short name', () => {
    const r = new Report('w', 'h')
    r.expect('a', true)
    expect(() => r.expect('a', false)).toThrow(/duplicate check name: a/)
    expect(() => r.scoped('p.').expect('a', true)).not.toThrow()
  })
})
