/**
 * Stage the implementation's proxy-rule set for publication (apps#420, plan
 * Decision 8: docs/superpowers/plans/2026-08-31-workflow-cli-authoring.md:24)
 * — `workflow publish`'s move 2.
 *
 * Ported from `bffless/publish-workflow` `scripts/prepare-rules.mjs` (fetched
 * read-only, not re-typed from memory). The behavior must stay byte-for-byte
 * equal to the action: the rule set as authored is prefix-free and named for
 * the implementation's own alias; what CE must receive is a set NAMED for the
 * alias (upload-artifact/`rules push` attaches it by name) whose routes live
 * under `/api/<alias>/` (the `--path-prefix` `runPublish` passes to `rules
 * push` does that at sync time), plus one generated rule the source must
 * never carry: the `/w/<alias>/*` forwarder that makes the harness host
 * serve this implementation's assets same-origin (ADR-0001).
 *
 * `ALIAS_RE`/`RESERVED_ALIASES` are NOT redeclared here — they're the exact
 * same constants ../rewrite.ts already ports from the same source file
 * (`renamePass` validates a new alias against them too), imported from there
 * so the two ports can never drift apart.
 *
 * Both edits happen on a COPY under a disposable temp dir — the source rule
 * set on disk is left untouched, so a re-run sees the same source it started
 * with.
 */
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path'
import { parseDocument, stringify } from 'yaml'
import { ALIAS_RE, RESERVED_ALIASES } from './rewrite.js'

/** The one rule this command generates. Authoring it by hand would be silently overwritten. */
const FORWARD_DIR = join('rules', '_custom', 'forward')
const FORWARD_FILE = 'get.rule.yaml'

/**
 * What the forwarder passes through to the implementation's own alias: CE's
 * default forward list plus the caller's credential. The target is CE itself
 * (a private alias sits behind the visibility gate), so the cookie *and* a
 * Bearer app token must both arrive — the edge and the in-process MCP invoker
 * apply this rule's own controls, and CE strips `authorization` unless listed
 * (bffless/ce#731).
 */
export const FORWARDER_HEADERS = {
  forward: [
    'accept',
    'accept-language',
    'content-type',
    'user-agent',
    'x-request-id',
    'cookie',
    'authorization',
  ],
  strip: ['host', 'connection', 'keep-alive', 'transfer-encoding'],
}

const forwarderDescription = (alias: string): string =>
  `Generated by @bffless/workflow publish: single-origin forwarding (ADR-0001) — /w/${alias}/[...path] ` +
  'on the harness host → the implementation alias, served in-process by the CE backend by ' +
  'default (no per-install domain).'

/**
 * The forwarder's `targetUrl` becomes a live proxy target, so it must be an
 * absolute http(s) origin — a bare host or a relative path would sync fine
 * and then 502 at request time.
 */
export function assertTargetUrl(targetUrl: string | undefined): void {
  if (!targetUrl) {
    throw new Error(
      'target-url is required: the resolved implementation alias target the forwarder ' +
        'points at (e.g. https://hello.j5s.dev, or the in-process default computed by ' +
        "runPublish's own target-url resolution).",
    )
  }
  let url: URL
  try {
    url = new URL(targetUrl)
  } catch {
    throw new Error(`target-url "${targetUrl}" is not an absolute URL (e.g. https://hello.j5s.dev)`)
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') {
    throw new Error(`target-url "${targetUrl}" must be http: or https: (got ${url.protocol})`)
  }
}

/** True when `child` is `parent` or lives underneath it. */
function contains(parent: string, child: string): boolean {
  const rel = relative(parent, child)
  return rel === '' || (rel !== '..' && !rel.startsWith('..' + sep) && !isAbsolute(rel))
}

/**
 * The staging directory is wiped before the copy, so it may not overlap the
 * source: an `outDir` equal to, inside, or containing the rule set would
 * delete the checkout.
 */
export function assertDisjoint(rulesDir: string, outDir: string | undefined): void {
  if (!outDir) throw new Error('--out is required: the directory to stage the rule set into')
  const src = resolve(rulesDir)
  const dst = resolve(outDir)
  if (contains(src, dst) || contains(dst, src)) {
    throw new Error(
      `--out "${outDir}" overlaps the rule set "${rulesDir}": the staging directory is ` +
        'deleted before the copy, so it must be somewhere else entirely (e.g. a temp dir).',
    )
  }
}

export function assertAlias(alias: string): void {
  if (!alias) throw new Error('alias is required')
  if (RESERVED_ALIASES.includes(alias)) {
    throw new Error(`alias "${alias}" is reserved (${RESERVED_ALIASES.join(', ')})`)
  }
  if (!ALIAS_RE.test(alias)) {
    throw new Error(`alias "${alias}" is not a valid alias: expected ${ALIAS_RE}`)
  }
}

export interface PrepareRulesArgs {
  rulesDir: string
  alias: string
  targetUrl: string
  outDir: string
}

/** Stages the rule set at `outDir` (== the return value): the alias-renamed copy plus the generated forwarder. */
export function prepareRules({ rulesDir, alias, targetUrl, outDir }: PrepareRulesArgs): string {
  assertAlias(alias)
  assertTargetUrl(targetUrl)
  if (!existsSync(join(rulesDir, 'ruleset.yaml'))) {
    throw new Error(`not a rule set (no ruleset.yaml): ${rulesDir}`)
  }
  if (existsSync(join(rulesDir, FORWARD_DIR))) {
    throw new Error(
      `${rulesDir}/${FORWARD_DIR} exists in source: the /w/<alias>/* forwarder is generated ` +
        'by @bffless/workflow publish — delete the authored copy.',
    )
  }

  assertDisjoint(rulesDir, outDir)

  // Replace, never merge: a re-run (or a second implementation reusing the
  // path) must not inherit a rule file the previous staging left behind — it
  // would be pushed as ours.
  rmSync(outDir, { recursive: true, force: true })
  mkdirSync(dirname(outDir), { recursive: true })
  cpSync(rulesDir, outDir, { recursive: true, force: true })

  // Rewrite only `name:` — comments, key order and `description:` survive, so
  // a `pull` of the pushed set still diffs cleanly against the source it came
  // from.
  const rulesetPath = join(outDir, 'ruleset.yaml')
  const doc = parseDocument(readFileSync(rulesetPath, 'utf8'))
  doc.set('name', alias)
  writeFileSync(rulesetPath, doc.toString())

  // An explicit `pathPattern:` is never touched by --path-prefix (CE CLI
  // build.ts: `manifest.pathPattern ?? applyPathPrefix(...)`), so
  // /w/<alias>/* survives the sync.
  const forwardDir = join(outDir, FORWARD_DIR)
  mkdirSync(forwardDir, { recursive: true })
  writeFileSync(
    join(forwardDir, FORWARD_FILE),
    stringify({
      pathPattern: `/w/${alias}/*`,
      targetUrl,
      forwardCookies: true,
      headerConfig: FORWARDER_HEADERS,
      order: 5,
      description: forwarderDescription(alias),
    }),
  )

  return outDir
}
